# $HOME/.zsh_profile/zsh_aliases.zsh
# Ensure custom binaries are available under sudo
alias sudo='sudo env "PATH=$PATH"'
alias nvim='sudo nvim'
alias freshZsh='source $HOME/.zshrc'
alias editZsh='sudo nano $HOME/.zshrc'
alias nvimZsh='sudo nvim $HOME/.zshrc'
alias nvimZshExports='sudo nvim $HOME/.zsh_profile/zsh_exports.zsh'
alias nvimZshGit='sudo nvim $HOME/.zsh_profile/zsh_git.zsh'
alias nvimZshMisc='sudo nvim $HOME/.zsh_profile/zsh_misc.zsh'
alias nvimZshConda='sudo nvim $HOME/.zsh_profile/zsh_conda.zsh'
alias nvimZshFunctions='sudo nvim ~/.zsh_profile/zsh_functions.zsh'
alias nvimZshPlugins='sudo nvim ~/.zsh_profile/zsh_plugins.zsh'
alias nvimZshAliases='sudo nvim ~/.zsh_profile/zsh_aliases.zsh'
alias nvimZshHistory='sudo nvim ~/.zsh_profile/zsh_history.zsh'
alias freshBash='source $HOME/.bashrc'
alias editBash='sudo nano $HOME/.bashrc'
alias nvimBash='sudo nvim $HOME/.bashrc'
alias sudoyay='yay --batchinstall --sudoloop --asdeps'
alias autoyay='yay --batchinstall --sudoloop --asdeps --noconfirm'
alias vimZsh='sudo vim ~/.zshrc'
alias getip="ip addr | grep 'inet ' | grep -v '127.0.0.1' | awk '{print \$2}' | cut -d/ -f1"
alias fzfind='fzf --print0 | xargs -0 -o nvim'
alias zsh_profile='/home/heini/.zshrc'
alias nvimInit='nvim ~/.config/nvim/init.lua'
alias ls='lsd'
alias startPyEnv='source /home/heini/Envs/pyEnv/bin/activate'
alias startPyVenv='source /home/heini/Envs/pyVenv/bin/activate'
alias startMyEnv='source /home/heini/Envs/myEnv/bin/activate'
alias batZsh='bat --paging=never --style=grid /home/heini/.zshrc'
#alias -g -- -h='-h 2>&1 | bat --language=help --style=plain'
#alias -g -- --help='--help 2>&1 | bat --language=help --style=plain'
alias catbat='"$(which bat)"'
